### ISSUE TITLE
Clarify licensing for test data

### ISSUE THREAD

**Issue by kalev** [Cykooz/libheif-rs#15]
During the package review for libheif-rs in Fedora, Fabio Valentini noted (https://bugzilla.redhat.com/bugzilla/show_bug.cgi?id=2235088#c2) that it's unclear what license applies to the test pictures in data/ directory. Could you add a note somewhere clarifying this, please? Most important for Fedora is that they are under a license that allows redistributing them; otherwise we'd have to roll a custom crate that excludes the files.

Thanks!

**Comment by Cykooz** [comment]
Is CC BY-SA 4.0 license will be good enough for Fedora?

**Comment by kalev** [comment]
Thanks! Yes, that's perfect. I think the main concern that Fabio had was that maybe the images are downloaded from somewhere and are actually not redistributable - anything from our https://docs.fedoraproject.org/en-US/legal/allowed-licenses/#_allowed_content_licenses is completely fine.

**Comment by Cykooz** [comment]
Ok, I'll replace couple of images whose license is unknown to me. After that I will add a file with license text into "data" directory.

**Comment by Cykooz** [comment]
I have released v0.21 with updated testing images under CC BY-SA 4.0 license.

**Comment by kalev** [comment]
Excellent, thank you!
