### ISSUE TITLE
Read from image bytes

### ISSUE THREAD

**Issue by ollyde** [Cykooz/libheif-rs#19]
We have ``let image_file_bytes: Vec<u8>`` in our control flow which is HEIC

How can we load it into the context without file?

`let lib_heif = LibHeif::new();`

**Comment by Cykooz** [comment]
[HeifContext::read_from_bytes()](https://docs.rs/libheif-rs/1.0.0/libheif_rs/struct.HeifContext.html#method.read_from_bytes)

**Comment by ollyde** [comment]
@Cykooz is there any convenience to convert this to PNG?

**Comment by Cykooz** [comment]
@ollyde 
- Decode image from HEIF
- Get buffer with RGB(A) pixels of decoded image. Or compose it from separate planes. It depends from image format.
- Encode buffer into PNG with help of crate like [image](https://crates.io/crates/image)

**Comment by ollyde** [comment]
@Cykooz thanks, I see the planes stuff on the home page; but it's confusing. Was hoping there was just a convert_to_format or something simple.

`https://github.com/Cykooz/libheif-rs`

**Comment by Cykooz** [comment]
You must use planes. It is raw buffer with pixels data.
```rust
let handle = context.primary_image_handle().unwrap();
let chroma = if handle.has_alpha_channel() {
    RgbChroma::Rgba
} else {
    RgbChroma::Rgb
};
let image = lib_hef.decode(&handle, ColorSpace::Rgb(chroma), None).unwrap();
let planes = image.planes();
if let Some(buffer) = planes.interleaved {
  // `buffer` is raw buffer with RGB(A) pixels
}
```

**Comment by ollyde** [comment]
@Cykooz thanks for you help, but it's too complex, decided to use image-magic, has a one liner for bytes :-)
