### ISSUE TITLE
How do I write a pre-encoded HEVC frame as a heif file using this library?

### ISSUE THREAD

**Issue by vi** [Cykooz/libheif-rs#5]
There are h265 NALs that should correspond to SPS, PPS and a keyframe.

How do I save them as HEIC file using this library, using only muxing to HEIF without the encoding step?

**Comment by Cykooz** [comment]
This crate is only a wrapper for library [libheif](https://github.com/strukturag/libheif). I have not found in ``libheif`` an API for adding encoded images into HEIF-container.
