### ISSUE TITLE
Unable to set encoder parameter values

### ISSUE THREAD

**Issue by wilsonzlin** [Cykooz/libheif-rs#7]
I'm currently trying to use this library to encode to AVIF, but can't find any way to set the speed parameter. I believe in libheif `heif_encoder_set_parameter_integer` is used, but I can't find any corresponding Rust method in this library. Is this possible?

**Comment by Cykooz** [comment]
Thank you for  your message.
I've made a new release of the crate.

```
[0.15.1] - 2022-10-21

Added method Encoder::set_parameter_value().
```

**Comment by wilsonzlin** [comment]
Thanks @Cykooz for the quick update!
