### ISSUE TITLE
Add support for color profiles

### ISSUE THREAD

**Issue by sophie-h** [Cykooz/libheif-rs#8]
Hey,

we are planning to use libheif-rs for GNOME's new image view Loupe. However, we need access to the color profiles. That would, especially the `get_color_profile_type`, `color_profile_nclx`, `raw_color_profile` functions. Can you make them available in the bindings or accept PRs?

**Comment by Cykooz** [comment]
Yes, I will make these functions.

**Comment by Cykooz** [comment]
@sophie-h Can you get me example of heic/heif image file with NCLX color profile for testing?

**Comment by sophie-h** [comment]
Yes, here is a .avif and .heif exported HDR (nCLX) image I have created with Krita for my testing.

https://gitlab.gnome.org/Incubator/loupe/uploads/322f81512346f3fd69b0acc502c04201/test.zip

**Comment by Cykooz** [comment]
I have released [libheif-rs 0.16.0](https://github.com/Cykooz/libheif-rs/releases/tag/v0.16.0)

Example of receiving color profile:
https://github.com/Cykooz/libheif-rs/blob/bb90749a90424c42991e3289ced03ca04ec92940/tests/read_test.rs#L255-L286

**Comment by sophie-h** [comment]
Hey! This is working great!

I have found some minor problems during implementation:

- Having `heif_image_get_bits_per_pixel_range` available for the channels would be handy.
- The `bits_pre_pixel` field probably has a typo? (pre -> per)
- `Planes` and `Plane` are not documented. Probably because they are not exported as types in `lib.rs` and the `image` module is not public

**Comment by Cykooz** [comment]
Thank you.
Look at the new release [libheif-rs 0.17.0](https://github.com/Cykooz/libheif-rs/releases/tag/v0.17.0)

**Comment by sophie-h** [comment]
Very cool. I think I got everything working now :)
