### ISSUE TITLE
Support for writing meta-data

### ISSUE THREAD

**Issue by sebastient** [Cykooz/libheif-rs#9]
The underlying libheif library supports writing meta-data such as exif and xmp into the output image.  Are there plans to support this or would a PR to present this API be considered?

**Comment by Cykooz** [comment]
I have released [libheif-rs 0.18.0](https://github.com/Cykooz/libheif-rs/releases/tag/v0.18.0)

Test with example of adding meta data:
https://github.com/Cykooz/libheif-rs/blob/49ab36a56eaa5564861d9fc3324c70bee53ca609/tests/write_test.rs#L126-L176
